### ISSUE TITLE
Fix mouth-open mirroring when user is speaking

### ISSUE THREAD

**Issue by elggem** [hansonrobotics/hr_reflexes#4]
- [ ] Pull apart the mirroring script into different pieces
  - [ ] Mirror mouth open only when person isn't talking, or introduce a multiplicator to make it less.

**Comment by jmossbridge** [comment]
Yes!  This would  be great -- right now she would be diagnosed with an impulse control problem or autism on the basis of the  mouth mirroring  during talking.

**Comment by elggem** [comment]
Fixed in commit https://github.com/hansonrobotics/hr_reflexes/commit/58c167bfc49043158d55e2f59aa828667acb3110

**Comment by jmossbridge** [comment]
Awesome, thanks Ralf!! You  are the rockstar of Loving AI!
